language: node_js
node_js:
- '5.6'
env:
  global:
  - GH_REF=github.com/mwaylabs/uikit
  - GH_USER=mwaysolutions
  - secure: RQN57Pp73HhmlLzw0LFhOZu9ooJTKIg3FF9eHANZ23Y5OHbhPEKEw8fzmapxdcC23ntvUwWiKGd9UL79my7UdZ8TmaJYGOaXikMGeXU6E5zNw+oa/yzv9nZXyvK6wObTJx4RJ6dTPKuaQfctCWvLNIlmC+GO/bKdFs674ENhoNr9/RDtB/scATb1Jm3HgUTx1l1zNSmO4J7motbBItklOvWq2vzYMeJu12o4Y9cKx5CGCVRf9vOzk8VeUSetRSQ6lp0DFE5jOsTU65mYZ0DKmKg9TRSn3Uq5uSSp47bMz75iz2Gzbkn26ffZmyutXophII4xjysOu4x8veCoyGcoXxEOBqkKK4oOYvSaJ9+OyGokFHhhVIlJVPxZ2Fo5+F0YyFy7XElcMldgy7Ad9qvvCAYgAk3FBrO3mYBF/kEvJJqWOAauFANkDEd30phm5znEYMe7H0qe+YCNKUCUjDQt90tuUj5+dI9q3Tyip6DQLtG90d9TdFi4zwTwVVFa7+YD6ViGhrDP0weKSF+VAG7bTNTyPg67XuTd3G71iWCWoTBTgx8GNTLUW79STpHXI0WbZ73vbpDMNSa/G0m452nNc0Q0Ruj1TJppTFnXujwEfTGEyNFrE/T9qXENK7bF0jjWzd74nLtWPUV2xzYuiXA33YhUHElTIOXrJZ5G8bPDEUA=
before_install:
- npm install -g bower
- npm install -g grunt-cli
- npm install -g karma
- bower install
deploy:
  - provider: script
    script: npm run release -- --buildNumber $TRAVIS_BUILD_NUMBER --commitHash $TRAVIS_COMMIT
    skip_cleanup: true 
    on: 
      repo: mwaylabs/uikit 
  - provider: releases 
    api_key: 
      secure: kcan/l0KlZPGb8BfP0ezlVt64Zj/w40OGQkGw7srAH1SFpsjqhici667MBlV2oJv0FtnCrzqNKQO5nn2K33i4amzV88H4CQFLMOCD46Koz6w7CzKRcX6Fh4fBE5c5CUkU/m5mutqI+K/deVNFCv8rCtY+xeQ0QA8ENmAVhBYlJpbRlzAJ6VZivXvol2CQIdA8h0YvQ9Y800EgsqpXuiai1wUhXBvihr+nk50n710cRVQbF/gLaXh6jr46UMJ70DO1oWzqUYP3AuO917P0lB3b+NIFs1p0P6f6Utgq2CEymg073KCBz44reMob2voCKK3yy46DClVPqNWodzW01XSQMJkiFafQgk0b8W72aMCVpOoRH09DXoSDRXuHzMnIujgtgRghMhsJjVh/9mRZUyP6fh5IZeeiClP9OdQZ1mFC6HbeZjQxaf6O6kmO4Gn6e5vtNZKE80wY9HK2MYUl3qpjZ6ETVnG0yBuTvu91knkp1Z/oq76TZwnKtKqamlxWEeU2xkZNXS1wTFZ6006NCvxGY9Rqmyb0aLV5evFaiNY9LPaNuuXkMJMMdlIOMHcBpQ9TuZUaZ76bRayr4yWVHKmc4joz5JzJm4lMLpv5u2jy+I2Lj79Ty9QI1vudlZZmibAECcHeqmb89F1NZpYIvFf8vgOgSkF7i3EHJld26tXtRI=
    file: zip/*.zip
    skip_cleanup: true 
    file_glob: true 
    on: 
      repo: mwaylabs/uikit 
  - provider: npm
    email: a.zarges@mwaysolutions.com
    api_key:
      secure: RmhcogeQ5XJ5LCG7v9LRd3WOB6BJW0b+7YE3+dk5UkfMgYVIu3sKccWfvv2+O0RV0+5VG8qyuJ5AK07AzVWIW+UIA/slaI9dU7rcl2/+sUT2tmQ0CTF44wvrbfB5e921zfxZTM7iqG4UxRea2RHtjQDi1nHRs9GsMicv/IN8lFFK7NZQv3QeOT23sewE7STXg6cbhSzQh1In3l+wOzv7+e8PjK9NFCOCXmSSKp2keTgFu9sdH8rLUQAo3ervSzgQW0Qtreey7IloD7vKgZP6WpI5Xj4+m6ck+D5z6QZ8+ht3u+7y8IHLJAmswyJcha0j8e18dMeZxa5qZuwzWu1r1Jr5wNKY6UuJ91hB0dedYfp5Kmq7+a2tIvQKOyO4UNfTCZAMa+Gou2RTDzhbCRph3gCkPmp/EAh68qsbdrdODvvfeL0w51eAukIWtbl7VL3vexpMNPuZcdf1liEmF0x80iLk5WqHlY56sFnjHyFLoBL5F73jHGXTQDF+SzHkJMA8O/Ohd1XJmIt6RFxDASlp/Sz5ebG2b3qTEgde10UtRuC6GXqnCXVnusdxBrRS6zNQeSjdTnWGqo1ugUQL+NEb9OwIR4SuL3V6PfR59sZXrQD0f7JoRhoEnODVBZLBdXrRbveIMo0g2PCdyBcmn0PRwWxLUJkbEW1KHduUeD2VqDQ=
    on:
      repo: mwaylabs/uikit 
