language: node_js
node_js:
- '5.6'
env:
  global:
  - GH_REF=github.com/mwaylabs/uikit
  - GH_USER=mwaysolutions
  - secure: Z1wAjmSApCB9uhIxK5d/TbSDbgwDa/gl0jMYtWDAthbwoqqLMc3NUvz4lQ1hW/S3bhNE1jw5dgV1bhh2ca2FBUgyR6iqGFarK64oiorYJITo+g0wblLbvSKHCoA2Zui+IRU0hEuSLApUnim0tUmBfV3V9gBo34LNBHfPv07Mt0yULgnPMMLEdmKV/QVIkJTO1G/am6h7+q5P+8jsdKM4NI18Yck9BZGsYtVwTnwXbfLoBeiMkCcjCBfPGC4R3rKQZ4M53D9L/lcbf2yypCvwK2QUilAwb1BPjS8uyu67oU44+slZcg8HgjDk0IgvSbAaGuAKkZtQOp8WTFOyA8zYr0uyPhT1PXTwBBOjPt9XIMrXZXghu1777EQ03eQJnQ9lWItuXrDuT70cmlcc5mYpMZ5+R6tiSDvReqkwfozFkxqkyMJANIDWWImAfcuMupDw7IPGA5khyGJQNnBVbsKLX/HTAKzZ1jyOlRarIJc5+dJptpPOvDC1TJq3OclD/IT5EqaUP4pBcW1NzcCx2vjyalb7cxyMy/X08Bmu6XUIo+wjzQoZl8+VBqDvJPKR+Bq8G2a+fERITNmzl/Cj4gyz+uYZsexvTY7u5z/4a7stPPX3bihxvlydVG44gFQVlhyhPPU3959matodOc5BosqpqazUOtvdwVFgFDRu4PgMtS0=
before_install:
- npm install -g bower
- npm install -g grunt-cli
- npm install -g karma
- bower install
deploy:
  - provider: script
    script: npm run release -- --buildNumber $TRAVIS_BUILD_NUMBER --commitHash $TRAVIS_COMMIT
    skip_cleanup: true 
    on: 
      repo: mwaylabs/uikit 
  - provider: releases 
    api_key: 
      secure: U7Nj098CpC9uONKTwY0+PJB0nsmIJS6MpP4sB6P22JALbQZ1DEewooFoZixEj0JZigYX8pIFVVTN9uEbJeacFd18MqmWelgqgGHw/RBEq4dqw2SW3iwomFxerpB0+1dTUE6iLIed4nRETnypg7Cxa8I+3cY8Ks3hLzuv37+3GhtBOd5ORtIpVKBjP19UFmyrRHNG/sazLNsLgO2ojmwiq29jhxSK/lN77UHZQF6UMlrs9zkfvyMLQjAwb/osoME8G0J0bRBNq1sAlTLeATREjY+tE7DZrNKOzEw3mEzShQBwEvqY06l0ccV3P2Aybowts/h68sUhKWS65wO24Q6fESJoW+wt8jIjdOGoiJtvw+Q/qwDUP0GbEGMzJFo/qHvJqL868EVSlXSCtkmCwpZWs5X20ywasyIZUU7zisQAjwyqUI0dJhKnElkvm0DDKbZuk6N7Pa6yicPY58uNlA5mBhpSHmcd5GcfTi6RlDHf/ITSeMYZOxFTvIaTpHgsPtBYG5H0LPaztRDcH33nlRqN1VZNtPfJQ3hq81WNIlbIsIi+vxEFplQMRFt8rHfUbTdefyzRcyiYOR8Tl114ZOV6nnqhT+4OQE+M1GSL3+Yj0OApdI5C8x3AxAUbMVARVfMLCTyZVNso2b9X60ak++LNdvgHR0qUvFjUkXQkOgIawVM=
    file: zip/*.zip
    skip_cleanup: true 
    file_glob: true 
    on: 
      repo: mwaylabs/uikit 
  - provider: npm
    email: a.zarges@mwaysolutions.com
    api_key:
      secure: zlB6m4IT0R3ta46jmh6K2EJp2cySvQeXUawLIbbuKWdxLLYb2FS3DEtW9SrwjkTNzmQ8Xk2DzrPj2yCkK2vQ6IPJHARx07sFZHb6DRF8ILkiMycMdffetgYGJ9UApnJ3ysrw0J4rMhI0uXtg4UVeil2dO69WlZYFIsNxF3TrdO5mKdMBiVlxLAh2xQYQya5/Y9It489O0deKEmQfmIBGfcujmLLpQZe15NSaD4mt9QqOV7rcEMm+4RaUDQn+1APhQWLvTkABHsz9NuNHYziu3t6nRimQcuxwOnLk9oyz1qNMo5K8Ajy/rw3xqI173rkbiJK5Lb6n/lBiXQ9h5Rp8syKrKjLX8utIejdjuuW5F/hUal2IC9lXIt3GOmIhNvgGNpSYz2tN2O0TIOQ13+jYM8SR6i6tijrfQnfaJZAQJ82OJvijkmKfDK1zgd3hIrUbSHMHgP+MGWjGX16ZATqnTGi0spRK0740TsxNfmt9Rb7xAnuESX6mTZZgyCH++ugqP4mloAORRONAIHFrILdivyRVaU9qxVhhOWpyFvbp+TiOSZy9awlgugLd262pkJ7/olzqVfJ2/jYOMDs6mC4C1m6oPs02tBn7n1CKriFQAo6Z/QJu6Me5YmSVTSmN53qmZKnU9McvP0PvbtKuDEBpoUDVkBb1HwZGPWkaRxQkDT0=
    on:
      repo: mwaylabs/uikit 
