language: node_js
node_js:
- '5.6'
env:
  global:
  - GH_REF: github.com/mwaylabs/uikit
  - secure: VOxlp4biAOjc+tqR1vgvxkKm92358HxaPMPdMA5t0fNK6jplkgj2eOi8+lwFaZStdSt0xME6MUN5cdbgEmdxfzfJAAa0FnnOvWWZDLD1dTWSHwlhFvHtrTBdQRNqzmehTNBg0jIIi8oxte9KCnhfyLhiX6qtuxQoqQSdBUMWrJUkcKrMEjI1U8GQXDh/6yZQnCqxS3jnotEFS2eDGyKRNNqfSd8p+MB4f903cAwoabyWJHxzNWOjvJf+0T4dTJp0mC4laOkes73lPU4fhpcPbvlRauKmoFqPUnRiHDzwZUIADAHx4oZmgBs7T5EHPr+BOWSeRRjjS+7/Qr9zRgcIm28/9S/o/qRqhsJxp7s+b0r8dXFGK9dV4j8vNHwT/wJE1CWF8waE/cDHnPcKorUXLNcNac0HLzvPT6QyBvtk+QDnvYP7fcSab6Xpw3QIXrmy9IePgokLF3bxyMdDC468IkYCrMIlrlyNbu/czp94ihh4i58t0lAQDO46U/nDmCh1c3SCaZlsEJXmgXlLkFHi498WGgCetpoWW0tBXqFB99ev29lARMqn+QbCgh5fmN29YTGxORsIs31StZ+azBV33GTogrPEKUQ9736kMGBDmJnUMsBGFKNeShnk8aTt1eI+pdmO3CuSAToSMovlX8g36k+I0ZQ3s8I9gkhYPBU9paU=
before_install:
- npm install -g bower
- npm install -g grunt-cli
- npm install -g karma
- bower install
before_deploy:
- npm run release -- --buildNumber $TRAVIS_BUILD_NUMBER --commitHash $TRAVIS_COMMIT
deploy:
  - provider: releases 
    api_key: 
      secure: VOxlp4biAOjc+tqR1vgvxkKm92358HxaPMPdMA5t0fNK6jplkgj2eOi8+lwFaZStdSt0xME6MUN5cdbgEmdxfzfJAAa0FnnOvWWZDLD1dTWSHwlhFvHtrTBdQRNqzmehTNBg0jIIi8oxte9KCnhfyLhiX6qtuxQoqQSdBUMWrJUkcKrMEjI1U8GQXDh/6yZQnCqxS3jnotEFS2eDGyKRNNqfSd8p+MB4f903cAwoabyWJHxzNWOjvJf+0T4dTJp0mC4laOkes73lPU4fhpcPbvlRauKmoFqPUnRiHDzwZUIADAHx4oZmgBs7T5EHPr+BOWSeRRjjS+7/Qr9zRgcIm28/9S/o/qRqhsJxp7s+b0r8dXFGK9dV4j8vNHwT/wJE1CWF8waE/cDHnPcKorUXLNcNac0HLzvPT6QyBvtk+QDnvYP7fcSab6Xpw3QIXrmy9IePgokLF3bxyMdDC468IkYCrMIlrlyNbu/czp94ihh4i58t0lAQDO46U/nDmCh1c3SCaZlsEJXmgXlLkFHi498WGgCetpoWW0tBXqFB99ev29lARMqn+QbCgh5fmN29YTGxORsIs31StZ+azBV33GTogrPEKUQ9736kMGBDmJnUMsBGFKNeShnk8aTt1eI+pdmO3CuSAToSMovlX8g36k+I0ZQ3s8I9gkhYPBU9paU=
    file: zip/*.zip 
    skip_cleanup: true 
    file_glob: true 
    on: 
      repo: mwaylabs/uikit 
  - provider: npm
    email: a.zarges@mwaysolutions.com
    api_key:
      secure: RmhcogeQ5XJ5LCG7v9LRd3WOB6BJW0b+7YE3+dk5UkfMgYVIu3sKccWfvv2+O0RV0+5VG8qyuJ5AK07AzVWIW+UIA/slaI9dU7rcl2/+sUT2tmQ0CTF44wvrbfB5e921zfxZTM7iqG4UxRea2RHtjQDi1nHRs9GsMicv/IN8lFFK7NZQv3QeOT23sewE7STXg6cbhSzQh1In3l+wOzv7+e8PjK9NFCOCXmSSKp2keTgFu9sdH8rLUQAo3ervSzgQW0Qtreey7IloD7vKgZP6WpI5Xj4+m6ck+D5z6QZ8+ht3u+7y8IHLJAmswyJcha0j8e18dMeZxa5qZuwzWu1r1Jr5wNKY6UuJ91hB0dedYfp5Kmq7+a2tIvQKOyO4UNfTCZAMa+Gou2RTDzhbCRph3gCkPmp/EAh68qsbdrdODvvfeL0w51eAukIWtbl7VL3vexpMNPuZcdf1liEmF0x80iLk5WqHlY56sFnjHyFLoBL5F73jHGXTQDF+SzHkJMA8O/Ohd1XJmIt6RFxDASlp/Sz5ebG2b3qTEgde10UtRuC6GXqnCXVnusdxBrRS6zNQeSjdTnWGqo1ugUQL+NEb9OwIR4SuL3V6PfR59sZXrQD0f7JoRhoEnODVBZLBdXrRbveIMo0g2PCdyBcmn0PRwWxLUJkbEW1KHduUeD2VqDQ=
    on:
      repo: mwaylabs/uikit
