language: node_js
node_js:
- '5.6'
env:
  global:
  - GH_REF: github.com/mwaylabs/uikit
  - secure: DvcBkunmRNzUUDHVgptgg7srR7N272/gzIoSCJhYXl1xFyDhgU5rWU0Robw7PM/WiewxB5OwJff2ecox/+/o/SYhqu5zSKv6gHv/Suq8vsMLKKETkhoD/lHgAEesY77Dn7oO9r3+fdZqq1vIzaUGDmi4/k2523NJpBhKuxv4uy2KtFrYbu85xIpXX0JjQA5nDVu93mbXmMEu63zcgSfH9oM14D8yJeXs+7iwFtAN7UR6T4273R1DRbBA8x7o7oBAKzFX9bNP3Hk8cS4EAUabUxouhQxZO4IRbrH6cOmpFM405dpBUjTYf4hmHpn5oHy7DJdNpM/hm47gZ6rg0ot9REWjjq0Cs8JISz3tbZWyChci8tqn91Ut5iljOkKPO15/ahOjXPjS3KeMmvb/hSK6Po860KwiA2h3wkTvkNIwlN5W8fFKKMkV294AAeTEyt6mJQyGmWNISPQ7r20/gbPYHYmhhkSIvvrLkxY6oemQMpfHpJlN18wsCQ0uJPm5VEr0xcPuholB6KiGo237OWtlO2xm4n2KLIRHL8OfHz2g9XywXku1F0biK2YQUscugWMUEWzW8kyXFET7poh3yMkPMlqS2m17q4nOiQbEPwSgVl7UkNFk/4ZBszGCvfRUeWKbSzKhME6EN97A30m7fw94WkCzDKMNJtGsusqDWjM+q1Q=
before_install:
- npm install -g bower
- npm install -g grunt-cli
- npm install -g karma
- bower install
deploy:
  - provider: script
    script: npm run release -- --buildNumber $TRAVIS_BUILD_NUMBER --commitHash $TRAVIS_COMMIT
    skip_cleanup: true 
    on: 
      repo: mwaylabs/uikit 
  - provider: releases 
    api_key: 
    secure: UaZRz3Ceu0P8YNzyPn6UH71gEfKXJJuEza1rEgIphevBu+jm42OvefC+rx0IUf2+y61bRJgJLNuZAWv5JPzm8m5jCicTunuf2QEXGWxj5qXUr6kwvyfY7D9RkRax5cuuy1BjKwS/GHKCYP/esAGYD8/uVY8oK1Dj91IxwVC+cMUGv44b4KQY4c5eW9pEdxFY0zwxxqnC2YTc5b4xU8+9y591QFW5d7UUA4RBhgcFmaPcsinDbFYagzHLQ/4osxkFhFUprHAQAa15vh5Z5d4wn4SjgPNqAhu/kIfm3sU7WrR61t8ruyqBJPkgYL3MfF7KZqZiNoekf1YWu/1qucTym5YNVs0T6X826v2BYTlbhFQoKek2ALNgjsxKNC1eKMiog7S7dJaCA9VoyNnCJnY0ne117cAVMnCrUx+BrgdbSsOjB4Cw/eLeBNwlYWrDxe4mJiRX4/U6kpzIi/MLkRbQTCbJFlog7ON4S89SzjvJOX8Sh8vZsDgMYxdXUgQHG7qyvXB+SklB6Vvb39tO44PXu2RrVGHBV3QGkNojmNXUQCKMRhEf76WRnrZUZanj6OOs5oy2m/5Z+H1RY06cXPA5tXsWS7dxhlS3JK2eWlcAkey2qlkQXQRmUXwB7a0COvIqBOnBA43vc9Bef/pIk2VAYN/OwE54TEj6e5pZqPSQwBk=
    file: zip/*.zip
    skip_cleanup: true 
    file_glob: true 
    on: 
      tags: true
      repo: mwaylabs/uikit 
  - provider: npm
    email: a.zarges@mwaysolutions.com
    api_key:
      secure: RmhcogeQ5XJ5LCG7v9LRd3WOB6BJW0b+7YE3+dk5UkfMgYVIu3sKccWfvv2+O0RV0+5VG8qyuJ5AK07AzVWIW+UIA/slaI9dU7rcl2/+sUT2tmQ0CTF44wvrbfB5e921zfxZTM7iqG4UxRea2RHtjQDi1nHRs9GsMicv/IN8lFFK7NZQv3QeOT23sewE7STXg6cbhSzQh1In3l+wOzv7+e8PjK9NFCOCXmSSKp2keTgFu9sdH8rLUQAo3ervSzgQW0Qtreey7IloD7vKgZP6WpI5Xj4+m6ck+D5z6QZ8+ht3u+7y8IHLJAmswyJcha0j8e18dMeZxa5qZuwzWu1r1Jr5wNKY6UuJ91hB0dedYfp5Kmq7+a2tIvQKOyO4UNfTCZAMa+Gou2RTDzhbCRph3gCkPmp/EAh68qsbdrdODvvfeL0w51eAukIWtbl7VL3vexpMNPuZcdf1liEmF0x80iLk5WqHlY56sFnjHyFLoBL5F73jHGXTQDF+SzHkJMA8O/Ohd1XJmIt6RFxDASlp/Sz5ebG2b3qTEgde10UtRuC6GXqnCXVnusdxBrRS6zNQeSjdTnWGqo1ugUQL+NEb9OwIR4SuL3V6PfR59sZXrQD0f7JoRhoEnODVBZLBdXrRbveIMo0g2PCdyBcmn0PRwWxLUJkbEW1KHduUeD2VqDQ=
    on:
      tags: true
      repo: mwaylabs/uikit 
