language: node_js
node_js:
- '5.6'
env:
  global:
  - GH_REF=github.com/mwaylabs/uikit
  - GH_USER=mwaysolutions
  - secure: MJU0YccoVu3cwlamvmdb0P73vbpYUbFT3sAyC4su0BQE3End30IzGl81Op7cOKWhYCN+UQRw4dDo8wwNwbbBCboyofDerKtkBWno/e+PBOr34bHK6FtClw2dwah0IWZjcjs+AECzU3W+zuofLpuMBFTy2LitPJ6jIIV6ivB+/c8ekSHI9pUgJBSet8NIcyjmMOsQeb2PIkKGcWvOaFX4/zgUqp3dCMvGyEgDFNEYhqh8qjwhcUQj4xzbWE8y3SZM/Qr3wSs5tY3pG18TAMWbRL4LOpUINIPs/FbeO27qhmZ/nnGrT+fyxEAno0d1BMi7oDw2/bq+DZtMjEemAdrynZH5+Dxeu++a6pigAua6MTfBF/wUvlgrTQHkoJeLc26ejC2HhLmZqLo9lHw2k2+JC444WiDyFqXT06IM+Ld73SUlWwR+tIhS3hXX4dzigf3YkteeIJFbQSCgQhbKMxiKsVCH1Uai0gIwAzW2rWUw9Rhq47C+F11YAMRAU1FeIea8NnH+Zq5F7rVo18KdWfO5gA64bfKUl1gx0z9IQ01BJveeU4oCyv99TPZND5F1OgCi5sB/BDofrRhGYGQ5WmV+yqZL8hf9dgulR0LSuAyjjXlk2gQkrfa54G7bQxZLUEB+KMlzUemowXUVZnMCxVr2zMDvAUUqbCRzoC/eot9qZa8=
before_install:
- npm install -g bower
- npm install -g grunt-cli
- npm install -g karma
- bower install
deploy:
  - provider: script
    script: npm run release -- --buildNumber $TRAVIS_BUILD_NUMBER --commitHash $TRAVIS_COMMIT
    skip_cleanup: true 
    on: 
      repo: mwaylabs/uikit 
  - provider: releases 
    api_key: 
      secure: kcan/l0KlZPGb8BfP0ezlVt64Zj/w40OGQkGw7srAH1SFpsjqhici667MBlV2oJv0FtnCrzqNKQO5nn2K33i4amzV88H4CQFLMOCD46Koz6w7CzKRcX6Fh4fBE5c5CUkU/m5mutqI+K/deVNFCv8rCtY+xeQ0QA8ENmAVhBYlJpbRlzAJ6VZivXvol2CQIdA8h0YvQ9Y800EgsqpXuiai1wUhXBvihr+nk50n710cRVQbF/gLaXh6jr46UMJ70DO1oWzqUYP3AuO917P0lB3b+NIFs1p0P6f6Utgq2CEymg073KCBz44reMob2voCKK3yy46DClVPqNWodzW01XSQMJkiFafQgk0b8W72aMCVpOoRH09DXoSDRXuHzMnIujgtgRghMhsJjVh/9mRZUyP6fh5IZeeiClP9OdQZ1mFC6HbeZjQxaf6O6kmO4Gn6e5vtNZKE80wY9HK2MYUl3qpjZ6ETVnG0yBuTvu91knkp1Z/oq76TZwnKtKqamlxWEeU2xkZNXS1wTFZ6006NCvxGY9Rqmyb0aLV5evFaiNY9LPaNuuXkMJMMdlIOMHcBpQ9TuZUaZ76bRayr4yWVHKmc4joz5JzJm4lMLpv5u2jy+I2Lj79Ty9QI1vudlZZmibAECcHeqmb89F1NZpYIvFf8vgOgSkF7i3EHJld26tXtRI=
    file: zip/*.zip
    skip_cleanup: true 
    file_glob: true 
    on: 
      tags: true
  - provider: npm
    email: a.zarges@mwaysolutions.com
    api_key:
      secure: RmhcogeQ5XJ5LCG7v9LRd3WOB6BJW0b+7YE3+dk5UkfMgYVIu3sKccWfvv2+O0RV0+5VG8qyuJ5AK07AzVWIW+UIA/slaI9dU7rcl2/+sUT2tmQ0CTF44wvrbfB5e921zfxZTM7iqG4UxRea2RHtjQDi1nHRs9GsMicv/IN8lFFK7NZQv3QeOT23sewE7STXg6cbhSzQh1In3l+wOzv7+e8PjK9NFCOCXmSSKp2keTgFu9sdH8rLUQAo3ervSzgQW0Qtreey7IloD7vKgZP6WpI5Xj4+m6ck+D5z6QZ8+ht3u+7y8IHLJAmswyJcha0j8e18dMeZxa5qZuwzWu1r1Jr5wNKY6UuJ91hB0dedYfp5Kmq7+a2tIvQKOyO4UNfTCZAMa+Gou2RTDzhbCRph3gCkPmp/EAh68qsbdrdODvvfeL0w51eAukIWtbl7VL3vexpMNPuZcdf1liEmF0x80iLk5WqHlY56sFnjHyFLoBL5F73jHGXTQDF+SzHkJMA8O/Ohd1XJmIt6RFxDASlp/Sz5ebG2b3qTEgde10UtRuC6GXqnCXVnusdxBrRS6zNQeSjdTnWGqo1ugUQL+NEb9OwIR4SuL3V6PfR59sZXrQD0f7JoRhoEnODVBZLBdXrRbveIMo0g2PCdyBcmn0PRwWxLUJkbEW1KHduUeD2VqDQ=
    on:
      tags: true
